"""Regenerate the first-install SQL snapshot from the ordered migrations."""
from pathlib import Path
import re

folder = Path(__file__).resolve().parent
parts = ["""-- Kyomei 2.3.22: FIRST INSTALL ONLY. See migrations/README.md.
-- Generated by build_first_install.py; edit the numbered migrations instead.
-- Replace YOUR_EMAIL_HERE with your administrator login email before running.
begin;
DO $$ BEGIN
  IF 'YOUR_EMAIL_HERE' = 'YOUR_' || 'EMAIL_HERE' THEN
    RAISE EXCEPTION 'Replace the administrator email placeholder before installing';
  END IF;
  IF to_regclass('public.sessions') IS NOT NULL THEN
    RAISE EXCEPTION 'Existing installation: apply numbered upgrades, not first_install.sql';
  END IF;
END $$;
"""]
for migration in sorted(folder.glob('[0-9][0-9][0-9]_*.sql')):
    # Each numbered upgrade is transactional on its own. The snapshot wraps all
    # of them in one transaction, so a failed install leaves no partial schema.
    sql = re.sub(r'^(?:begin;|commit;)\s*$', '', migration.read_text(), flags=re.M)
    parts.append(f'-- Source: {migration.name}\n{sql}')
parts.append('commit;\n')
(folder / 'first_install.sql').write_text('\n'.join(parts))
